### ISSUE TITLE
array_unique() a bunch of `stdClass`es leads to fatal error  (and exit)

### ISSUE THREAD

**Issue by jens1o** [bobthecow/psysh#434]
```
PS C:\nginx\html\projects\php-ffmpeg-org\PHP-FFMpeg> psysh
Psy Shell v0.8.14 (PHP 7.2.0RC5 — cli) by Justin Hilemanan
How are you doing sir? c:
>>> $r = []
=> []
>>> $s = new stdClass
=> {#213}
>>> $r[] = $s
=> {#213}
>>> $r[] = $s
=> {#213}
>>> $r
=> [
     {#213},
     {#213},
   ]
>>> array_unique($r)
PHP Warning:  Uncaught Psy\Exception\ErrorException: PHP Recoverable fatal error:  Object of class stdClass could not be converted to string on line 1 in :1
Stack trace:
#0 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php(820): Psy\Exception\ErrorException::throwException(4096, 'Object of class...', 'C:\\Users\\Jens\\A...', 1)
#1 [internal function]: Psy\Shell->handleError(4096, 'Object of class...', 'C:\\Users\\Jens\\A...', 1, Array)
#2 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code(1): array_unique(Array)
#3 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90): eval()
#4 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(146): Psy\ExecutionLoop\{closure}(Object(Psy\Shell))
#5 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php(294): Psy\ExecutionLoop\Loop->run(Object(Psy\Shell))
#6 C:\Users\Jens\AppData\Roaming\Composer\vendor\symfony\console\ in Unknown on line 1

Warning: Uncaught Psy\Exception\ErrorException: PHP Recoverable fatal error:  Object of class stdClass could not be converted to string on line 1 in :1
Stack trace:
#0 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php(820): Psy\Exception\ErrorException::throwException(4096, 'Object of class...', 'C:\\Users\\Jens\\A...', 1)
#1 [internal function]: Psy\Shell->handleError(4096, 'Object of class...', 'C:\\Users\\Jens\\A...', 1, Array)
#2 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code(1): array_unique(Array)
#3 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90): eval()
#4 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(146): Psy\ExecutionLoop\{closure}(Object(Psy\Shell))
#5 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php(294): Psy\ExecutionLoop\Loop->run(Object(Psy\Shell))
#6 C:\Users\Jens\AppData\Roaming\Composer\vendor\symfony\console\ in Unknown on line 1
PHP Fatal error:  Object of class stdClass could not be converted to string in C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code on line 1

Fatal error: Object of class stdClass could not be converted to string in C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code on line 1
```

**Comment by bobthecow** [comment]
This is an issue with PHP in general… 

<img width="762" alt="screen shot 2018-02-11 at 9 59 32 pm" src="https://user-images.githubusercontent.com/53660/36084969-da64a092-0f76-11e8-9bc2-a0acf3028c2d.png">

I'm not sure how much PsySH could do to avoid this, other than injecting runtime checks into functions like `array_unique` that have implicit string conversions :-/

**Comment by theofidry** [comment]
@bobthecow I wouldn't personally expect PsySH to modify the behaviour of those functions to add extra checks. My only complain here is that the exit is quite brutal.

Maybe having a error handler registered (if none is already registered) to not exit but display the error instead?

**Comment by bobthecow** [comment]
yeah, i agree. i wasn't suggesting we _do_ that, just saying it's probably the only way it can be done :)
