### ISSUE TITLE
Deprecated functions throw ErrorException and so quits the shell

### ISSUE THREAD

**Issue by jens1o** [bobthecow/psysh#468]
```
PS C:\Users\Jens> psysh
Psy Shell v0.8.17 (PHP 7.2.2 — cli) by Justin Hileman
How are you doing sir? c:
>>> class Test {
... public function test() : ? array {
... return null;
... }
... }
PHP Warning:  Uncaught Psy\Exception\ErrorException: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Test has a deprecated constructor on line 1 in :1
Stack trace:
#0 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php(820): Psy\Exception\ErrorException::throwException(8192, 'Methods with th...', 'C:\\Users\\Jens\\A...', 1)
#1 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90): Psy\Shell->handleError(8192, 'Methods with th...', 'C:\\Users\\Jens\\A...', 1, Array)
#2 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90): eval()
#3 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(146): Psy\ExecutionLoop\{closure}(Object(Psy\Shell))
#4 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php(294): Psy\ExecutionLoop\Loop->run(Object(Psy\Shell))
#5 C:\Users\Jens\AppData\Roaming\Composer\vendor\symfony\console\Appli in (null) on line 1
PHP Stack trace:
PHP   1. {main}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:0
PHP   2. Psy\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:135
PHP   3. Psy\Shell->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\functions.php:325
PHP   4. Psy\Shell->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:258
PHP   5. Psy\Shell->doRun() C:\Users\Jens\AppData\Roaming\Composer\vendor\symfony\console\Application.php:143
PHP   6. Psy\ExecutionLoop\Loop->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:294
PHP   7. Psy\ExecutionLoop\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php:146

Warning: Uncaught Psy\Exception\ErrorException: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Test has a deprecated constructor on line 1 in :1
Stack trace:
#0 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php(820): Psy\Exception\ErrorException::throwException(8192, 'Methods with th...', 'C:\\Users\\Jens\\A...', 1)
#1 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90): Psy\Shell->handleError(8192, 'Methods with th...', 'C:\\Users\\Jens\\A...', 1, Array)
#2 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90): eval()
#3 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(146): Psy\ExecutionLoop\{closure}(Object(Psy\Shell))
#4 C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php(294): Psy\ExecutionLoop\Loop->run(Object(Psy\Shell))
#5 C:\Users\Jens\AppData\Roaming\Composer\vendor\symfony\console\Appli in (null) on line 1

Call Stack:
    0.0009     399752   1. {main}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:0
    0.0197     487328   2. Psy\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:135
    0.1415    1774392   3. Psy\Shell->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\functions.php:325
    0.1506    1935816   4. Psy\Shell->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:258
    0.2146    1943392   5. Psy\Shell->doRun() C:\Users\Jens\AppData\Roaming\Composer\vendor\symfony\console\Application.php:143
    0.2167    1944264   6. Psy\ExecutionLoop\Loop->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:294
    0.2167    1945032   7. Psy\ExecutionLoop\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php:146

PHP Fatal error:  Constructor Test::test() cannot declare a return type in C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code on line 1
PHP Stack trace:
PHP   1. {main}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:0
PHP   2. Psy\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:135
PHP   3. Psy\Shell->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\functions.php:325
PHP   4. Psy\Shell->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:258
PHP   5. Psy\Shell->doRun() C:\Users\Jens\AppData\Roaming\Composer\vendor\symfony\console\Application.php:143
PHP   6. Psy\ExecutionLoop\Loop->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:294
PHP   7. Psy\ExecutionLoop\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php:146

Fatal error: Constructor Test::test() cannot declare a return type in C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php(90) : eval()'d code on line 1

Call Stack:
    0.0009     399752   1. {main}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:0
    0.0197     487328   2. Psy\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\bin\psysh:135
    0.1415    1774392   3. Psy\Shell->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\functions.php:325
    0.1506    1935816   4. Psy\Shell->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:258
    0.2146    1943392   5. Psy\Shell->doRun() C:\Users\Jens\AppData\Roaming\Composer\vendor\symfony\console\Application.php:143
    0.2167    1944264   6. Psy\ExecutionLoop\Loop->run() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\Shell.php:294
    0.2167    1945032   7. Psy\ExecutionLoop\{closure}() C:\Users\Jens\AppData\Roaming\Composer\vendor\psy\psysh\src\Psy\ExecutionLoop\Loop.php:146
```

**Comment by bobthecow** [comment]
In this case, the issue is the error at the bottom: because you're using a "same method name as class name" legacy constructor, you get a deprecation warning, but it keeps working.

The real issue is that you define a return time for your legacy constructor, but legacy constructors can't have a return type. You can confirm this by removing the return type for that method:

<img width="762" alt="screen shot 2018-02-10 at 6 44 33 am" src="https://user-images.githubusercontent.com/53660/36063152-f0f12a1e-0e2d-11e8-9d6b-58e379ebaa90.png">

I'd highly recommend not using legacy constructors. They're weird. You can do this by not naming methods the same as the class, or by defining your class in a namespace:

<img width="762" alt="screen shot 2018-02-10 at 6 47 05 am" src="https://user-images.githubusercontent.com/53660/36063185-6cc63d1e-0e2e-11e8-8118-54f0a377cd44.png">

… or by providing an explicit constructor:

<img width="762" alt="screen shot 2018-02-10 at 6 47 44 am" src="https://user-images.githubusercontent.com/53660/36063187-785fb466-0e2e-11e8-9601-b21a84ea18bd.png">

**Comment by jens1o** [comment]
Yeah, I do know my issue, but imo, it should not quit the shell, but handle the case adorable.

**Comment by bobthecow** [comment]
Unfortunately not quitting the shell isn't possible with uncatchable fatal errors on Windows, and apparently adding a return type to a constructor is an uncatchable fatal error.

**Comment by jens1o** [comment]
Okay, thanks for your reply. Closing, as it is unfixable in the current state.

**Comment by bobthecow** [comment]
Ha! Got a fix:

<img width="938" alt="screen shot 2018-02-10 at 4 36 21 pm" src="https://user-images.githubusercontent.com/53660/36068045-91231c48-0e80-11e8-8670-d69791e10a66.png">

**Comment by bobthecow** [comment]
Alright. I've got a workaround that seems to be okay. It'll be in the next stable release. Thanks for reporting!

**Comment by jens1o** [comment]
Oh, I didn't expected that. Thanks!

**Comment by bobthecow** [comment]
No problem :)
