### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by branquito** [bobthecow/psysh#99]
Getting this error when trying to run `psysh` from terminal.

`Segmentation fault (core dumped)`. What might be the problem.

**Comment by dequis** [comment]
Hey! I had the same segfault issue, debugged it a bit and submitted a bug report with patch here: https://bugs.php.net/bug.php?id=69054

More specifically, I got the following ErrorException from laravel:

```
$ php artisan tinker
exception 'ErrorException' with message 'is_file(): open_basedir restriction in effect. File(/etc/xdg/psysh/config.php) is not within the allowed path(s): (/srv/http/:/home/:/tmp/:/usr/share/pear/)' in /home/dx/test/asd/sonar/laravel/vendor/psy/psysh/src/Psy/Configuration.php:132
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'is_file(): open...', '/home/dx/test/a...', 132, Array)
#1 /home/dx/test/asd/sonar/laravel/vendor/psy/psysh/src/Psy/Configuration.php(132): is_file('/etc/xdg/psysh/...')
#2 /home/dx/test/asd/sonar/laravel/vendor/psy/psysh/src/Psy/Configuration.php(105): Psy\Configuration->getConfigFile()
#3 /home/dx/test/asd/sonar/laravel/vendor/psy/psysh/src/Psy/Configuration.php(89): Psy\Configuration->init()
#4 /home/dx/test/asd/sonar/laravel/vendor/psy/psysh/src/Psy/Shell.php(68): Psy\Configuration->__construct()
#5 /home/dx/test/asd/sonar/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/TinkerCommand.php(31): Psy\Shell->__construct()
#6 [internal function]: Illuminate\Foundation\Console\TinkerCommand->fire()
#7 /home/dx/test/asd/sonar/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#8 /home/dx/test/asd/sonar/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
#9 /home/dx/test/asd/sonar/laravel/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/dx/test/asd/sonar/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/dx/test/asd/sonar/laravel/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/dx/test/asd/sonar/laravel/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\TinkerCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/dx/test/asd/sonar/laravel/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/dx/test/asd/sonar/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/dx/test/asd/sonar/laravel/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main}
```

When I workarounded it by adding `@` before `is_file` to ignore the errors, i got the segfault instead.

**Comment by bobthecow** [comment]
Would it make sense to parse open_basedir restrictions and try to avoid looking for config files outside the open_basedir folders? How much complication should we add to work around a bug in PHP?

**Comment by dequis** [comment]
The segfault is really nasty so I think it's worth workarounding it. Parsing open_basedir isn't needed - that would only prevent the ErrorException, which i believe you can get the same effect by prepending @ to the is_file. You should probably check if open_basedir is defined when calling `readline_read_history()` to avoid the segfault

And... after writing that I figured I could send those changes as a pull request, so here: https://github.com/bobthecow/psysh/pull/150

**Comment by dequis** [comment]
Bug fixed here https://github.com/php/php-src/commit/a620b7904023202b8b4a5d7792368bd752c432e9 (will be in the next point release)
